### PR TITLE
allow usage of custom instance

### PR DESCRIPTION
**Pull request by airtonix**

### CODE REVIEW

**Comment by tmcw** [comment]
Awesome, can you add this to the JSDoc as an additional param?

**Comment by airtonix** [comment]
@tmcw is `{Function}` or  `{Object}` the right type?

**Comment by tmcw** [comment]
`Object` is the correct type

**Comment by airtonix** [comment]
I looked into doing a test for this, but :
- time value ratio seemed quite low for something that would be ultimately the responsibility of the end user.
- how would we require two versions of `documentation.js`  for circle-ci to install?

**Comment by tmcw** [comment]
Yeah, the CircleCI angle would be tricky. I'm fine with this being just simple and not having test coverage yet. Merging.

**Pull request merged**
